datagrid:
    issues-grid:
        extended_entity_name: %sbts.issue.entity.class%
        source:
            type: orm
            query:
                select:
                    - issue.id
                    - issue.summary
                    - issue.description
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - reporter.id as reporterId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - assignee.id as assigneeId
                    - issue.createdAt
                    - issue.updatedAt
                    - issuePriority.id as priorityId
                    - issuePriority.name as priorityName
                    - issueType.id as typeId
                    - issueType.name as typeName
                    - issueResolution.id as resolutionId
                    - issueResolution.name as resolutionName
                from:
                    - { table: %sbts.issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.issue_priority, alias: issuePriority }
                        - { join: issue.issue_type, alias: issueType }
                        - { join: issue.issue_resolution, alias: issueResolution }
        columns:
            id:
                label:         sbts.issue.label.id
            summary:
                label:         sbts.issue.label.summary
            type:
                label:         sbts.issue.label.type
                type:          twig
                frontend_type: html
                template:      SbtsIssueBundle:Issue:Datagrid/Property/type.html.twig
            priority:
                label:         sbts.issue.label.priority
                type:          twig
                frontend_type: html
                template:      SbtsIssueBundle:Issue:Datagrid/Property/priority.html.twig
            resolution:
                label:         sbts.issue.label.resolution
                type:          twig
                frontend_type: html
                template:      SbtsIssueBundle:Issue:Datagrid/Property/resolution.html.twig
            reporterName:
                type:          twig
                label:         sbts.issue.label.reporter
                frontend_type: html
                template:      SbtsIssueBundle:Issue:Datagrid/Property/reporter.html.twig
            assigneeName:
                type:          twig
                label:         sbts.issue.label.assignee
                frontend_type: html
                template:      SbtsIssueBundle:Issue:Datagrid/Property/assignee.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                id:
                    data_name: issue.id
                summary:
                    data_name: issue.summary
                type:
                    data_name: typeName
                priority:
                    data_name: priorityName
                resolution:
                    data_name: resolutionName
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                summary:
                    type:      string
                    data_name: issue.summary
                type:
                    type:      enum
                    data_name: typeId
                    enum_code: issue_type
                priority:
                    type:      enum
                    data_name: priorityId
                    enum_code: issue_priority
                resolution:
                    type:      enum
                    data_name: resolutionId
                    enum_code: issue_resolution
                reporterName:
                    type:      string
                    data_name: reporterName
                assigneeName:
                    type:      string
                    data_name: assigneeName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        options:
            entity_pagination: true
        properties:
            id: ~
            view_link:
                type:   url
                route:  sbts_issue_view
                params: [ id ]
            update_link:
                type:   url
                route:  sbts_issue_update
                params: [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  sbts_issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  sbts_issue_update
                label:         oro.grid.action.view
                icon:          edit
                link:          update_link
                rowAction:     true
