datagrid:
    issues-grid:
        extended_entity_name: %sbts.issue.entity.class%
        source:
            type: orm
            query:
                select:
                    - issue.id
                    - issue.summary
                    - issue.description
                    - type.label as typeLabel
                    - priority.label as priorityLabel
                    - resolution.label as resolutionLabel
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - reporter.id as reporterId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - assignee.id as assigneeId
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: %sbts.issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.type, alias: type }
                        - { join: issue.priority, alias: priority }
                        - { join: issue.resolution, alias: resolution }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
        columns:
            id:
                label:         sbts.issue.label.id
            summary:
                label:         sbts.issue.label.summary
            typeLabel:
                label:         sbts.issue.label.type
            priorityLabel:
                label:         sbts.issue.label.priority
            resolutionLabel:
                label:         sbts.issue.label.resolution
            reporterName:
                type:          twig
                label:         sbts.issue.label.reporter
                frontend_type: html
                template:      SbtsIssueBundle:Issue:Datagrid/Property/reporter.html.twig
            assigneeName:
                type:          twig
                label:         sbts.issue.label.assignee
                frontend_type: html
                template:      SbtsIssueBundle:Issue:Datagrid/Property/assignee.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                id:
                    data_name: issue.id
                summary:
                    data_name: issue.summary
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                id: DESC
        filters:
            columns:
                summary:
                    type:      string
                    data_name: issue.summary
                typeLabel:
                    type:      string
                    data_name: typeLabel
                priorityLabel:
                    type:      string
                    data_name: priorityLabel
                resolutionLabel:
                    type:      string
                    data_name: resolutionLabel
                reporterName:
                    type:      string
                    data_name: reporterName
                assigneeName:
                    type:      string
                    data_name: assigneeName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        options:
            entity_pagination: true
        properties:
            id: ~
            view_link:
                type:   url
                route:  sbts_issue_view
                params: [ id ]
            update_link:
                type:   url
                route:  sbts_issue_update
                params: [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  sbts_issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  sbts_issue_update
                label:         oro.grid.action.view
                icon:          edit
                link:          update_link
                rowAction:     true
