parameters:
    sbts_issue.form.type.issue.class:    Sbts\Bundle\IssueBundle\Form\Type\IssueType
    sbts_issue.form.handler.issue.class: Sbts\Bundle\IssueBundle\Form\Handler\IssueHandler

services:
    sbts_issue.form.type.issue:
        class: %sbts_issue.form.type.issue.class%
        tags:
            - { name: form.type, alias: sbts_issue }

    sbts_issue.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'sbts_issue'
            - 'sbts_issue'

    sbts_issue.form.handler.issue:
        class: %sbts_issue.form.handler.issue.class%
        scope: request
        arguments:
            - @sbts_issue.form
            - @request
            - @doctrine.orm.entity_manager
            - @oro_activity.manager
            - @oro_entity.routing_helper
