parameters:
    sbts.importexport.template_fixture.issue.class: Sbts\Bundle\IssueBundle\ImportExport\TemplateFixture\IssueFixture

services:
    sbts.importexport.data_converter:
        parent: oro_importexport.data_converter.configurable

    sbts.importexport.template_fixture.data_converter.issue:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    sbts.importexport.strategy.issue.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    sbts.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@sbts.importexport.data_converter]]
             - [setStrategy, [@sbts.importexport.strategy.issue.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %sbts.issue.entity.class%, alias: sbts.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %sbts.issue.entity.class%, alias: sbts.add_or_replace }

    # Export processor
    sbts.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@sbts.importexport.data_converter]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %sbts.issue.entity.class%, alias: sbts }

    sbts.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@sbts.importexport.template_fixture.data_converter.issue]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %sbts.issue.entity.class%, alias: sbts }

    sbts.importexport.template_fixture.issue:
        class: %sbts.importexport.template_fixture.issue.class%
        tags:
            - { name: oro_importexport.template_fixture }
