parameters:
#    sbts_issue.example.class: Sbts\Bundle\IssueBundle\Example

services:
#    sbts_issue.example:
#        class: %sbts_issue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
