parameters:
    sbts.issue.entity.class: Sbts\Bundle\IssueBundle\Entity\Issue
    sbts.issue.listener.class: Sbts\Bundle\IssueBundle\EventListener\IssueListener

services:
    sbts_issue.listener:
        class: %sbts.issue.listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
