sbts_issue_bundle:
    resource: "@SbtsIssueBundle/Controller"
    type: annotation
    prefix: /sbts

sbts_issue_bundle_api:
    resource:     "@SbtsIssueBundle/Resources/config/oro/routing_api.yml"
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest
